### ISSUE TITLE
setxy in DataSet

### ISSUE THREAD

**Issue by m0ose** [backspaces/asx#26]
The camel case of setxy does not match the rest. Shouldn't it be setXY.
There is still getXY, toXY
https://github.com/backspaces/asx/blob/a85171f2c19e1369bf265042494a4c17ec925cc9/src/core/DataSet.js#L62

**Comment by backspaces** [comment]
Yup. Bingo!

One issue is the 3D change. Not sure if setxy, setxyz, or setPosition would
be best. But in dataset, setXY or setxy would be logical.

To tell the truth, I've been such a hermit, I'm no longer clear on what
would be best! I think netlogo had a set-xy for turtles so it the
historical reason setxy or setXY naming was used.

Thank you for catching this.

**Comment by backspaces** [comment]
OK, just changed setxy -> setXY in dataset.

In turtles I left it as setxy because it should be setxyz maybe? I don't think we've nailed down our 3D semantics yet so it may change to setPosition or similar.
